# Generated by Django 4.1.2 on 2023-02-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_alter_vehicleentry_fair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_method_response', models.JSONField(blank=True, max_length=500, null=True)),
                ('pm_type', models.CharField(blank=True, max_length=50)),
                ('card_no', models.CharField(blank=True, max_length=20)),
                ('exp_month', models.CharField(blank=True, max_length=10)),
                ('exp_year', models.CharField(blank=True, max_length=10)),
                ('cvv_no', models.CharField(blank=True, max_length=10)),
                ('billing_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('currency', models.CharField(blank=True, max_length=25)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
            ],
        ),
    ]
