# Generated by Django 4.1.2 on 2023-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
