# Generated by Django 4.1.2 on 2023-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmethod_name_on_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
