# Generated by Django 4.1.2 on 2023-02-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vehicleentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='fair',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
