# Generated by Django 4.1.2 on 2023-02-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vehicleentry_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='stripe_customer_response',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
