# Generated by Django 4.1.2 on 2023-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_accounts_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='slot_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
